// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf7pUDtoPlVMQ4sAnrI_qtpwWdkOR9ALQ',
    appId: '1:1089055201889:web:2cda604045801f49e9e820',
    messagingSenderId: '1089055201889',
    projectId: 'first-firebase-a4809',
    authDomain: 'first-firebase-a4809.firebaseapp.com',
    databaseURL: 'https://first-firebase-a4809-default-rtdb.firebaseio.com',
    storageBucket: 'first-firebase-a4809.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCalkAyXnaAEu3acgXSxWpkrXqToCA87wg',
    appId: '1:1089055201889:android:d24896e87cd375e4e9e820',
    messagingSenderId: '1089055201889',
    projectId: 'first-firebase-a4809',
    databaseURL: 'https://first-firebase-a4809-default-rtdb.firebaseio.com',
    storageBucket: 'first-firebase-a4809.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsHdoIVRGvsJpVpDzQinsRI-wlUwTtOq8',
    appId: '1:1089055201889:ios:98c8452e4b3b1cd0e9e820',
    messagingSenderId: '1089055201889',
    projectId: 'first-firebase-a4809',
    databaseURL: 'https://first-firebase-a4809-default-rtdb.firebaseio.com',
    storageBucket: 'first-firebase-a4809.appspot.com',
    androidClientId: '1089055201889-a7dmqio6ah14ih0r00eukucaojr31h3n.apps.googleusercontent.com',
    iosClientId: '1089055201889-doggs0khrp1rappquunn9r2c1377p2d5.apps.googleusercontent.com',
    iosBundleId: 'com.example.donations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsHdoIVRGvsJpVpDzQinsRI-wlUwTtOq8',
    appId: '1:1089055201889:ios:7eabb640315a3c64e9e820',
    messagingSenderId: '1089055201889',
    projectId: 'first-firebase-a4809',
    databaseURL: 'https://first-firebase-a4809-default-rtdb.firebaseio.com',
    storageBucket: 'first-firebase-a4809.appspot.com',
    androidClientId: '1089055201889-a7dmqio6ah14ih0r00eukucaojr31h3n.apps.googleusercontent.com',
    iosClientId: '1089055201889-5thq2qlk1f9u6bf4jrh1nur3idcfgg6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.donations.RunnerTests',
  );
}
